# Keyboard Modifiers
class KeyboardMods:
    MOD_LEFT_CTRL = (1 << 8)
    MOD_LEFT_SHIFT = (1 << 9)
    MOD_LEFT_ALT = (1 << 10)
    MOD_LEFT_GUI = (1 << 11)
    MOD_RIGHT_CTRL = (1 << 12)
    MOD_RIGHT_SHIFT = (1 << 13)
    MOD_RIGHT_ALT = (1 << 14)
    MOD_RIGHT_GUI = (1 << 15)

# Keyboard Leds
class KeyboardLeds:
    LED_NUM_LOCK = (1 << 0)
    LED_CAPS_LOCK = (1 << 1)
    LED_SCROLL_LOCK = (1 << 2)
    LED_COMPOSE = (1 << 3)
    LED_KANA = (1 << 4)
    LED_POWER = (1 << 5)
    LED_SHIFT = (1 << 6)
    LED_DO_NOT_DISTURB = (1 << 7)

# Keyboard Keycode
class KeyboardKeycode:
    KEY_RESERVED = 0
    KEY_ERROR_ROLLOVER = 1
    KEY_POST_FAIL = 2
    KEY_ERROR_UNDEFINED = 3
    KEY_A = 4
    KEY_B = 5
    KEY_C = 6
    KEY_D = 7
    KEY_E = 8
    KEY_F = 9
    KEY_G = 10
    KEY_H = 11
    KEY_I = 12
    KEY_J = 13
    KEY_K = 14
    KEY_L = 15
    KEY_M = 16
    KEY_N = 17
    KEY_O = 18
    KEY_P = 19
    KEY_Q = 20
    KEY_R = 21
    KEY_S = 22
    KEY_T = 23
    KEY_U = 24
    KEY_V = 25
    KEY_W = 26
    KEY_X = 27
    KEY_Y = 28
    KEY_Z = 29
    KEY_1 = 30
    KEY_2 = 31
    KEY_3 = 32
    KEY_4 = 33
    KEY_5 = 34
    KEY_6 = 35
    KEY_7 = 36
    KEY_8 = 37
    KEY_9 = 38
    KEY_0 = 39
    KEY_ENTER = 40
    KEY_RETURN = 40  # Alias
    KEY_ESC = 41
    KEY_BACKSPACE = 42
    KEY_TAB = 43
    KEY_SPACE = 44
    KEY_MINUS = 45
    KEY_EQUAL = 46
    KEY_LEFT_BRACE = 47
    KEY_RIGHT_BRACE = 48
    KEY_BACKSLASH = 49
    KEY_NON_US_NUM = 50
    KEY_SEMICOLON = 51
    KEY_QUOTE = 52
    KEY_TILDE = 53
    KEY_COMMA = 54
    KEY_PERIOD = 55
    KEY_SLASH = 56
    KEY_CAPS_LOCK = 0x39
    KEY_F1 = 0x3A
    KEY_F2 = 0x3B
    KEY_F3 = 0x3C
    KEY_F4 = 0x3D
    KEY_F5 = 0x3E
    KEY_F6 = 0x3F
    KEY_F7 = 0x40
    KEY_F8 = 0x41
    KEY_F9 = 0x42
    KEY_F10 = 0x43
    KEY_F11 = 0x44
    KEY_F12 = 0x45
    KEY_PRINT = 0x46
    KEY_PRINTSCREEN = 0x46  # Alias
    KEY_SCROLL_LOCK = 0x47
    KEY_PAUSE = 0x48
    KEY_INSERT = 0x49
    KEY_HOME = 0x4A
    KEY_PAGE_UP = 0x4B
    KEY_DELETE = 0x4C
    KEY_END = 0x4D
    KEY_PAGE_DOWN = 0x4E
    KEY_RIGHT_ARROW = 0x4F
    KEY_LEFT_ARROW = 0x50
    KEY_DOWN_ARROW = 0x51
    KEY_UP_ARROW = 0x52
    KEY_RIGHT = 0x4F  # Alias
    KEY_LEFT = 0x50  # Alias
    KEY_DOWN = 0x51  # Alias
    KEY_UP = 0x52  # Alias
    KEY_NUM_LOCK = 0x53
    KEYPAD_DIVIDE = 0x54
    KEYPAD_MULTIPLY = 0x55
    KEYPAD_SUBTRACT = 0x56
    KEYPAD_ADD = 0x57
    KEYPAD_ENTER = 0x58
    KEYPAD_1 = 0x59
    KEYPAD_2 = 0x5A
    KEYPAD_3 = 0x5B
    KEYPAD_4 = 0x5C
    KEYPAD_5 = 0x5D
    KEYPAD_6 = 0x5E
    KEYPAD_7 = 0x5F
    KEYPAD_8 = 0x60
    KEYPAD_9 = 0x61
    KEYPAD_0 = 0x62
    KEYPAD_DOT = 0x63
    KEY_NON_US = 0x64
    KEY_APPLICATION = 0x65  # Context menu/right click
    KEY_MENU = 0x65  # Alias
    KEY_POWER = 0x66  # PowerOff (Ubuntu)
    KEY_PAD_EQUALS = 0x67  # Don't confuse with KEYPAD_EQUAL_SIGN
    KEY_F13 = 0x68  # Tools (Ubuntu)
    KEY_F14 = 0x69  # Launch5 (Ubuntu)
    KEY_F15 = 0x6A  # Launch6 (Ubuntu)
    KEY_F16 = 0x6B  # Launch7 (Ubuntu)
    KEY_F17 = 0x6C  # Launch8 (Ubuntu)
    KEY_F18 = 0x6D  # Launch9 (Ubuntu)
    KEY_F19 = 0x6E  # Disabled (Ubuntu)
    KEY_F20 = 0x6F  # AudioMicMute (Ubuntu)
    KEY_F21 = 0x70  # Touchpad toggle (Ubuntu)
    KEY_F22 = 0x71  # TouchpadOn (Ubuntu)
    KEY_F23 = 0x72  # TouchpadOff (Ubuntu)
    KEY_F24 = 0x73  # Disabled (Ubuntu)
    KEY_EXECUTE = 0x74  # Open (Ubuntu)
    KEY_HELP = 0x75  # Help (Ubuntu)
    KEY_MENU2 = 0x76  # Disabled (Ubuntu)
    KEY_SELECT = 0x77  # Disabled (Ubuntu)
    KEY_STOP = 0x78  # Cancel (Ubuntu)
    KEY_AGAIN = 0x79  # Redo (Ubuntu)
    KEY_UNDO = 0x7A  # Undo (Ubuntu)
    KEY_CUT = 0x7B  # Cut (Ubuntu)
    KEY_COPY = 0x7C  # Copy (Ubuntu)
    KEY_PASTE = 0x7D  # Paste (Ubuntu)
    KEY_FIND = 0x7E  # Find (Ubuntu)
    KEY_MUTE = 0x7F
    KEY_VOLUME_MUTE = 0x7F  # Alias
    KEY_VOLUME_UP = 0x80
    KEY_VOLUME_DOWN = 0x81
    KEY_LOCKING_CAPS_LOCK = 0x82  # Disabled (Ubuntu)
    KEY_LOCKING_NUM_LOCK = 0x83  # Disabled (Ubuntu)
    KEY_LOCKING_SCROLL_LOCK = 0x84  # Disabled (Ubuntu)
    KEYPAD_COMMA = 0x85  # .
    KEYPAD_EQUAL_SIGN = 0x86  # Don't confuse with KEYPAD_EQUAL
    KEY_INTERNATIONAL1 = 0x87  # Disabled (Ubuntu)
    KEY_INTERNATIONAL2 = 0x88  # Hiragana Katakana (Ubuntu)
    KEY_INTERNATIONAL3 = 0x89  # Disabled (Ubuntu)
    KEY_INTERNATIONAL4 = 0x8A  # Henkan (Ubuntu)
    KEY_INTERNATIONAL5 = 0x8B  # Muhenkan (Ubuntu)
    KEY_INTERNATIONAL6 = 0x8C  # Disabled (Ubuntu)
    KEY_INTERNATIONAL7 = 0x8D  # Disabled (Ubuntu)
    KEY_INTERNATIONAL8 = 0x8E  # Disabled (Ubuntu)
    KEY_INTERNATIONAL9 = 0x8F  # Disabled (Ubuntu)
    KEY_LANG1 = 0x90  # Disabled (Ubuntu)
    KEY_LANG2 = 0x91  # Disabled (Ubuntu)
    KEY_LANG3 = 0x92  # Katakana (Ubuntu)
    KEY_LANG4 = 0x93  # Hiragana (Ubuntu)
    KEY_LANG5 = 0x94  # Disabled (Ubuntu)
    KEY_LANG6 = 0x95  # Disabled (Ubuntu)
    KEY_LANG7 = 0x96  # Disabled (Ubuntu)
    KEY_LANG8 = 0x97  # Disabled (Ubuntu)
    KEY_LANG9 = 0x98  # Disabled (Ubuntu)
    KEY_ALT_ERASE = 0x99  # Disabled (Ubuntu)
    KEY_SYSREQ = 0x9A  # Disabled (Ubuntu)
    KEY_CANCEL = 0x9B  # Disabled (Ubuntu)
    KEY_CLEAR = 0x9C  # Delete (Ubuntu)
    KEY_PRIOR = 0x9D  # Disabled (Ubuntu)
    KEY_RETURN2 = 0x9E  # Disabled (Ubuntu)
    KEY_SEPARATOR = 0x9F  # Disabled (Ubuntu)
    KEY_OUT = 0xA0  # Disabled (Ubuntu)
    KEY_OPER = 0xA1  # Disabled (Ubuntu)
    KEY_CLEAR_AGAIN = 0xA2  # Disabled (Ubuntu)
    KEY_CRSEL = 0xA3  # Disabled (Ubuntu)
    KEY_EXSEL = 0xA4  # Disabled (Ubuntu)
